# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='operation',
        ),
        migrations.AddField(
            model_name='calculations',
            name='operator',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
