# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0002_auto_20200701_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculations',
            old_name='operator',
            new_name='result',
        ),
    ]
